config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'top#index'
  resources :top, only: :index
  resources :users, only: [:index, :show] do
    collection do
      get :setting
      get :nickname
      get :profileimage
      get :profile
      get :gameprofile
      get :email
    end
    member do
      get :followed, :followers, :recommend
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :boards do
    resources :comments, only: [:create, :destroy] 
  end
  resources :posts, only: [:new, :create]
  resources :rooms, only: [:index, :create, :show]
  resources :direct_messages, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :board_console_relations, dependent: :destroy
  has_many :board_category_relations, dependent: :destroy
  has_many :consoles, through: :board_console_relations
  has_many :categories, through: :board_category_relations

  validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :user_category_relations
  has_many :board_category_relations
  has_many :post_category_relations
  has_many :users, through: :user_category_relations
  has_many :boards, through: :board_category_relations
  has_many :posts, through: :post_category_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :content, presence: true, length: { in: 1..1000 }
end

app/models/console.rb
class Console < ApplicationRecord
  has_many :user_console_relations
  has_many :board_console_relations
  has_many :post_console_relations
  has_many :users, through: :user_console_relations
  has_many :boards, through: :board_console_relations
  has_many :posts, through: :post_console_relations
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :boards
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user
  has_many :post_console_relations, dependent: :destroy
  has_many :post_category_relations, dependent: :destroy
  has_many :consoles, through: :post_console_relations
  has_many :categories, through: :post_category_relations

  validates :message, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: { case_sensitive: true }, length: { maximum: 15 }

  has_one_attached :image
  has_many :boards
  has_many :comments

  has_many :user_console_relations
  has_many :consoles, through: :user_console_relations
  has_many :user_category_relations
  has_many :categories, through: :user_category_relations

  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy

  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :followers, through: :follower_relationships

  def self.guest
    find_or_create_by(nickname: 'ゲスト', email: 'guest@example.com', profile: "ゲストのプロフィール") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def followed?(other_user)
    followed_relationships.find_by(followed_id: other_user.id)
  end

  def follow(other_user)
    followed_relationships.create!(followed_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = followed_relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:message, :game_id, console_ids: [], category_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :recommend_function

  def index
    @boards = Board.order(created_at: 'DESC').limit(5)
    @posts = Post.order(created_at: 'DESC').limit(5)
    @user = current_user
    @category_ranks = Category.find(UserCategoryRelation.group(:category_id).order('count(category_id)desc').where.not(category_id: 10).pluck(:category_id))
  end

  def recommend_function
    if user_signed_in?
      user = current_user
      userCategories = user.user_category_relations
      myCategoryIds = []
      userCategories.each do |cate|
        myCategoryIds << cate.category.id
      end
      otherUserCategory = UserCategoryRelation.where(category_id: myCategoryIds).where('user_id !=?', user.id)
      otherUserIds = []
      otherUserCategory.each do |cate|
        otherUserIds << cate.user.id
      end
      userConsoles = user.user_console_relations
      myConsoleIds = []
      userConsoles.each do |con|
        myConsoleIds << con.console.id
      end
      otherUserConsole = UserConsoleRelation.where(console_id: myConsoleIds).where('user_id !=?', user.id)
      otherUserConsole.each do |con|
        otherUserIds << con.user.id
      end
      followedIds = user.followed_ids
      otherUserIds -= followedIds
      otherUserIds_uniq = otherUserIds.uniq
      @similar_user_limit = User.where(id: otherUserIds_uniq).limit(5)
      @similar_users = User.where(id: otherUserIds_uniq).page(params[:page]).per(10)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/index.html.erb
<%# <%= render "shared/second_header" %>

<div class="top-wrapper">
  <div class="top-left">
    <div class="top-right">
      <div class="rank-title">人気カテゴリー</div>
      <ul class="rank-wrap c-box">
        <% @category_ranks.each.with_index(1) do |e, i| %>
          <%= link_to "#" do %>
            <li class="rank-item">
              <div class="rank-tag-num"><%= "#{i}: " %></div> 
              <div class="rank-name"><%= e.name %></div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="top-center">
    <div class="top-board">
      <div class="all-thread c-box">
        <p class="top-board-title">新着掲示板一覧</p>
        <ul class="top-thread-list">
          <% @boards.each do |board| %>
            <li>
              <%= link_to board_path(board.id) do %>
                <div class="thread-title"><%= board.title %></div>
                <div class="info-line">
                  <span class="comment-left"><%= time_ago_in_words(board.created_at) + '前' %></span>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
        <%= link_to '掲示板一覧', boards_path, class: "board-link" %>
      </div>
      <%= link_to '新規掲示板作成', new_board_path %>
    </div>

    <div class="top-post">
      <div class="all-post c-box">
        <p class="top-board-title">メンバー募集</p>
        <div class="top-post-wrapper">
          <% @posts.each do |post| %>
            <div class="top-post-list">
              <ul class="top-post-over">
                <li class="top-post-name"><%= link_to post.user.nickname, user_path(post.user_id) %></li>
                <li class="comment-left">・<%= time_ago_in_words(post.created_at) + '前' %></li>
              </ul>
              <ul class="top-post-bottom">
                <li class="top-post-content"><%= safe_join(post.message.split("\n"),tag(:br)) %></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
      <%= link_to '新規作成', new_post_path %>
    </div>
  </div>

  <div class="top-right">
    <% if user_signed_in? %>
      <div class="show-right">
        <div class="show-right-top">
          <div class="recommend-title">
            <p>おすすめユーザー</p>
            <p><%= link_to 'ユーザー一覧', users_path %></p>
          </div>
          <%= link_to recommend_user_path(@user.id), class: "recommend-link" do %>
            <span class="recommend-link-text">もっと見る</span>
            <div>
              <%= image_tag 'sharp_keyboard_arrow_right_black_18dp.png', :size => '23x23' %>
            </div>
          <% end %>
        </div>
        <ul class="recommend-user-wrap c-box">
          <% @similar_user_limit.each do |e| %>
            <li class="recommend-user-item">
              <div class="recommend-user-left">
                <% if e.image.present? %>
                  <div class="recommend-user-image"><%= image_tag e.image, class: "recommend-img img-back" %></div>
                <% else %>
                  <div class="recommend-user-image"><%= image_tag "test.png", class: "recommend-img" %></div>
                <% end %>
              </div>
              <div class="recommend-user-right">
                <%= link_to e.nickname, user_path(e.id) %>
                <p><%= e.profile %></p>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>