config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'top#index'
  resources :top, only: :index
  resources :users, only: [:index, :show] do
    collection do
      get :setting
      get :nickname
      get :profileimage
      get :profile
      get :gameprofile
      get :email
    end
    member do
      get :followed, :followers, :recommend
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :boards do
    resources :comments, only: [:create, :destroy] 
  end
  resources :posts, only: [:new, :create]
  resources :rooms, only: [:index, :create, :show]
  resources :direct_messages, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: { case_sensitive: true }, length: { maximum: 15 }

  has_one_attached :image
  has_many :boards
  has_many :comments

  has_many :user_console_relations
  has_many :consoles, through: :user_console_relations
  has_many :user_category_relations
  has_many :categories, through: :user_category_relations

  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy

  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :followers, through: :follower_relationships

  def self.guest
    find_or_create_by(nickname: 'ゲスト', email: 'guest@example.com', profile: "ゲストのプロフィール") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def followed?(other_user)
    followed_relationships.find_by(followed_id: other_user.id)
  end

  def follow(other_user)
    followed_relationships.create!(followed_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = followed_relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: [:update, :destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(_resource)
    user_path(@user.id)
  end

  def check_guest
    if resource.email == 'guest@example.com' || resource.nickname == 'ゲスト'
      redirect_to root_path, alert: 'ゲストユーザーは変更・削除できません。'
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:setting, :nickname]
  before_action :set_user, only: [:show, :followed, :followers, :recommend]
  before_action :recommend_function, only: [:show, :recommend]
  before_action :set_user_edit, only: [:nickname, :profile, :gameprofile, :profileimage, :email]

  def index
    @q = User.ransack(params[:q])
    if user_signed_in?
      @users = User.all.where.not(id: current_user.id).page(params[:page]).per(10)
      @results = @q.result(distinct: true).page(params[:page]).per(10)
    else
      @users = User.all.page(params[:page]).per(10)
      @results = @q.result(distinct: true).page(params[:page]).per(10)
    end
  end

  def show
    @follow_limit = @user.followed.limit(6)
    @consoles = @user.consoles
    @categories = @user.categories

    # roomの相手ユーザーの取得
    @userEntries = @user.entries
    myRoomIds = []
    @userEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id !=?', @user.id)
    if user_signed_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id
              @existRoom = true
              @roomId = cu.room_id
            end
          end
        end
        unless @isRoom
          @room = Room.new
          @entry = Entry.new
        end
      end
    end

    # 書き込んだ掲示板取得
    @create_boards = @user.boards
    @comments = @user.comments
    myBoardIds = []
    @comments.each do |com|
      myBoardIds << com.board.id
    end
    @write_boards = Board.where(id: myBoardIds)
  end

  def setting
    render layout: 'user_edit'
  end

  def nickname
  end

  def profile
  end

  def gameprofile
  end

  def profileimage
  end

  def email
  end

  def followed
    @users = @user.followed.page(params[:page]).per(10)
  end

  def followers
    @users = @user.followers.page(params[:page]).per(10)
  end

  def recommend
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def recommend_function
    if user_signed_in?
      user = current_user
      userCategories = user.user_category_relations
      myCategoryIds = []
      userCategories.each do |cate|
        myCategoryIds << cate.category.id
      end
      otherUserCategory = UserCategoryRelation.where(category_id: myCategoryIds).where('user_id !=?', user.id)
      otherUserIds = []
      otherUserCategory.each do |cate|
        otherUserIds << cate.user.id
      end
      userConsoles = user.user_console_relations
      myConsoleIds = []
      userConsoles.each do |con|
        myConsoleIds << con.console.id
      end
      otherUserConsole = UserConsoleRelation.where(console_id: myConsoleIds).where('user_id !=?', user.id)
      otherUserConsole.each do |con|
        otherUserIds << con.user.id
      end
      followedIds = user.followed_ids
      otherUserIds -= followedIds
      otherUserIds_uniq = otherUserIds.uniq
      @similar_user_limit = User.where(id: otherUserIds_uniq).limit(5)
      @similar_users = User.where(id: otherUserIds_uniq).page(params[:page]).per(10)
    end
  end

  def set_user_edit
    @user = current_user
    render layout: 'user_edit'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_contact.html.erb
<% if user_signed_in? %>
  <% unless @user.id == current_user.id %>
    <% if @existRoom == true %>
      <%= link_to "チャットへ", room_path(@roomId) %>
    <% else %>
      <%= form_with model: @room, local: true do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "チャットを送る" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn following-btn" %>
<% end %>

app/views/users/_follow_count.html.erb
<div class="follow">
  <%= link_to followed_user_path(@user.id) do %>
    <ul>
      <li>フォロー</li>
      <li><%= @user.followed.count %>人</li>
    </ul>
  <% end %>
</div>
<hr>
<div class="follower">
  <%= link_to followers_user_path(@user.id) do %>
    <ul>
      <li>フォロワー</li>
      <li><%= @user.followers.count %>人</li>
    </ul>
  <% end %>
</div>

app/views/users/_follow_form.html.erb
<div id="follow-form">
  <% if current_user.followed?(@user) %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
</div>

app/views/users/_form_search.html.erb
<div class="panel-heading">
  <div class="panel-title">検索</div>
</div>
<div class="panel-body">
  <%= search_form_for @q do |f| %>
    <div class="row">
      <div class="form-group form-setting">
        <%= f.label :nickname_cont, "ニックネーム" %>
        <%= f.text_field :nickname_cont, class: "form-control" %>
      </div>

      <div class="form-group form-setting">
        <%= f.label :profile_cont, "プロフィール" %>
        <%= f.search_field :profile_cont, class: "form-control" %>
      </div>

    </div>
    <%= f.submit '検索', class: "btn btn-primary" %>
    <%= link_to 'クリア', url_for, class: "btn btn-default" %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true, data: { confirm: 'フォローを解除しますか？' }) do |f| %>
  <%= f.submit "フォロー中", class: "btn followed-btn" %>
<% end %>

app/views/users/email.html.erb
<div class="setting-main-top c-box">
  <p>ユーザー名変更</p>
  <%= form_with model: @user, url: user_registration_path, html: { method: :put }, local: true do |f| %>
    <div class="field">
      <div>
        <label class="form-text">メールアドレス</label>
      </div>
      <%= f.email_field :email, class:"input-default", autofocus: true, autocomplete: "email" %>
    </div>
    <div class="btn update-btn actions">
      <%= f.submit "変更する", class:"update-in-btn" %>
    </div>
  <% end %>
</div>

<div class="setting-main-bottom c-box">
  <%= link_to user_path(current_user.id), class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">プロフィールに戻る</span>
  <% end %>
  <%= link_to setting_users_path, class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">設定一覧に戻る</span>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="recommend-index">
  <div class="room-main-left">
    <p><%= link_to "トップページに戻る", root_path, class:"edit-link" %></p>
    <% if user_signed_in? %>
      <p><%= link_to "マイページに戻る", user_path(current_user.id),class:"edit-link" %></p>
    <% end %>
    <p><%= link_to "ユーザー一覧へ", users_path, class:"edit-link" %></p>
  </div>
  <div class="user-show">
    <div class="show-right-top">
      <div class="recommend-title">フォロー一覧</div>
    </div>
    <ul class="recommend-user-wrap c-box">
      <% @users.each do |e| %>
        <li class="recommend-user-item">
          <div class="recommend-user-left">
            <% if e.image.present? %>
              <div class="recommend-user-image"><%= image_tag e.image, class: "recommend-img img-back" %></div>
            <% else %>
              <div class="recommend-user-image"><%= image_tag "test.png", class: "recommend-img" %></div>
            <% end %>
          </div>
          <div class="recommend-user-right">
            <%= link_to e.nickname, user_path(e.id) %>
            <p><%= e.profile %></p>
          </div>
        </li>
      <% end %>
    </ul>
    <span><%= paginate @users %></span>
  </div>
</div>

app/views/users/gameprofile.html.erb
<div class="setting-main-top c-box">
  <p>ゲーム設定</p>
  <%= form_with model: @user, url: user_registration_path, html: { method: :put }, local: true do |f| %>
    <div class="field">
      <label class="form-text">持っている機器</label>
      <div class='checkboxes checkbox-top'>
        <%= f.collection_check_boxes(:console_ids, Console.all, :id, :name) do |b| %>
          <label class='checkbox-console'><%= b.label {b.check_box + b.text} %></label>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label class="form-text">好きなジャンル</label>
      <div class='checkboxes checkbox-middle'>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
          <label class='checkbox-category'><%= b.label {b.check_box + b.text} %></label><br>
        <% end %>
      </div>
    </div>
    <div class="btn update-btn actions">
      <%= f.submit "変更する", class:"update-in-btn" %>
    </div>
  <% end %>
</div>

<div class="setting-main-bottom c-box">
  <%= link_to user_path(@user.id), class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">プロフィールに戻る</span>
  <% end %>
  <%= link_to setting_users_path, class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">設定一覧に戻る</span>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="recommend-index">
  <div class="index-top">
    <p><%= link_to "トップページに戻る", root_path, class:"edit-link" %></p>
    <% if user_signed_in? %>
      <p><%= link_to "おすすめユーザー一覧へ", recommend_user_path(current_user.id),class:"edit-link" %></p>
      <p><%= link_to "マイページへ", user_path(current_user.id),class:"edit-link" %></p>
    <% end %>
  </div>
  <div class="index-bottom">
    <div class="panel panel-default">
      <%= render "form_search" %>
    </div>
    <div class="user-show">
      <ul class="users-wrap c-box">
        <% if params[:q].present? %>
          <div class="index-title">検索結果</div>
          <% if @results.empty? %>
            <p class="index-board-title">該当のユーザーが存在しません。</p>
          <% end %>
          <% @results.each do |e| %>
            <li class="recommend-user-item">
              <div class="recommend-user-left">
                <% if e.image.present? %>
                <div class="recommend-user-image"><%= image_tag e.image, class: "recommend-img img-back" %></div>
                <% else %>
                  <div class="recommend-user-image"><%= image_tag "test.png", class: "recommend-img" %></div>
                <% end %>
              </div>
              <div class="recommend-user-right">
                <%= link_to e.nickname, user_path(e.id) %>
                <p><%= e.profile %></p>
              </div>
            </li>
          <% end %>
          <span><%= paginate @results %></span>
        <% else %>
          <div class="index-title">ユーザー一覧</div>
          <% @users.each do |e| %>
            <li class="recommend-user-item">
              <div class="recommend-user-left">
                <% if e.image.present? %>
                <div class="recommend-user-image"><%= image_tag e.image, class: "recommend-img img-back" %></div>
                <% else %>
                  <div class="recommend-user-image"><%= image_tag "test.png", class: "recommend-img" %></div>
                <% end %>
                </div>
              <div class="recommend-user-right">
                <%= link_to e.nickname, user_path(e.id) %>
                <p><%= e.profile %></p>
              </div>
            </li>
          <% end %>
          <span><%= paginate @users %></span>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/nickname.html.erb
<div class="setting-main-top c-box">
  <p>ユーザー名変更</p>
  <%= form_with model: @user, url: user_registration_path, html: { method: :put }, local: true do |f| %>
    <div class="field">
      <div>
        <label class="form-text">ニックネーム</label>
      </div>
      <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"15文字以内", maxlength:"40", autofocus: true %>
    </div>
    <div class="btn update-btn actions">
      <%= f.submit "変更する", class:"update-in-btn" %>
    </div>
  <% end %>
</div>

<div class="setting-main-bottom c-box">
  <%= link_to user_path(@user.id), class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">プロフィールに戻る</span>
  <% end %>
  <%= link_to setting_users_path, class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">設定一覧に戻る</span>
  <% end %>
</div>

app/views/users/profileimage.html.erb
<div class="setting-main-top c-box">
  <p>プロフィール画像変更</p>
  <%= form_with model: @user, url: user_registration_path, html: { method: :put }, local: true do |f| %>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :imaga %>
    </div>
    <div class="btn update-btn actions">
      <%= f.submit "変更する", class:"update-in-btn" %>
    </div>
  <% end %>
</div>

<div class="setting-main-bottom c-box">
  <%= link_to user_path(@user.id), class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">プロフィールに戻る</span>
  <% end %>
  <%= link_to setting_users_path, class: "return-link" do %>
    <div>
      <%= image_tag 'baseline_keyboard_arrow_left_black_18dp.png', :size => '23x23' %>
    </div>
    <span class="recommend-link-text">設定一覧に戻る</span>
  <% end %>
</div>

app/views/users/recommend.html.erb
<div class="recommend-index">
  <div class="page-link">
    <p><%= link_to "トップページに戻る", root_path, class:"edit-link" %></p>
    <% if user_signed_in? %>
      <p><%= link_to "ユーザー一覧へ", users_path,class:"edit-link" %></p>
      <p><%= link_to "マイページへ", user_path(current_user.id),class:"edit-link" %></p>
    <% end %>
  </div>
  <div class="user-show">
    <div class="show-right-top">
      <div class="recommend-title">おすすめユーザー一覧</div>
    </div>
    <ul class="recommend-user-wrap c-box">
      <% @similar_users.each do |e| %>
        <li class="recommend-user-item">
          <div class="recommend-user-left">
            <div class="recommend-user-image">image</div>
          </div>
          <div class="recommend-user-right">
            <%= link_to e.nickname, user_path(e.id) %>
            <p><%= e.profile %></p>
          </div>
        </li>
      <% end %>
    </ul>
    <span><%= paginate @similar_users %></span>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-wrap">
  <div class="show-left">
    <div class="show-left-top c-box">
      <div class="profile-wrap">
        <div class="profile-left">
          <% if @user.image.present? %>
            <div class="image-circle"><%= image_tag @user.image, class: "profile-img img-back" %></div>
          <% else %>
            <div class="image-circle"><%= image_tag "test.png", class: "profile-img" %></div>
          <% end %>
          <div class="follow-show" id="js-follow-show">
            <%= render "follow_count" %>
          </div>
        </div>
        <div class="profile-right">
          <ul class="profile-top">
            <li class="profile-name"><%= @user.nickname %></li>
            <% if user_signed_in? %>
              <% if current_user.id == @user.id %>
                <li class="profile-setting"><%= link_to '設定', setting_users_path %></li>
              <% else %>
                <%= render "follow_form" %>
              <% end %>
            <% end %>
          </ul>
          <hr>
          <div class="profile-category">
            <label class="profile-label">使用機器:</label>
            <p><%= @consoles.map(&:name).join ', ' %></p>
            <label class="profile-label">好きなジャンル:</label>
            <p><%= @categories.map(&:name).join ', ' %></p>
          </div>
          <div class="profile-content">
            <label class="profile-label">自己紹介文:<br></label>
            <p class="profile-text"><%= safe_join(@user.profile.split("\n"),tag(:br)) %></p>
          </div>
        </div>
      </div><hr>

      <div class="following-users">
        <div class="show-right-top">
          <div class="recommend-title">フォローしている人</div>
          <%= link_to followed_user_path(@user.id), class: "recommend-link" do %>
            <span class="recommend-link-text">もっと見る</span>
            <div>
              <%= image_tag 'sharp_keyboard_arrow_right_black_18dp.png', :size => '23x23' %>
            </div>
          <% end %>
        </div>
        <div class="following-wrap">
          <% if @user.followed.present? %>
            <% @follow_limit.each do |e| %>
              <%= link_to user_path(e.id) do %>
                  <div class="following-user-item">
                    <% if e.image.present? %>
                      <div class="following-image"><%= image_tag e.image, class: "following-img img-back" %></div>
                    <% else %>
                      <div class="following-image"><%= image_tag "test.png", class: "following-img" %></div>
                    <% end %>
                    <p><%= e.nickname %></p>
                  </div>
              <% end %>
            <% end %>
          <% else %>
            <p class="no-following">まだフォローしている人はいません。</p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="show-bottom">
      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="show-bottom-left show-bottom-items c-box">
          <p>DM</p>
          <ul>
            <% @anotherEntries.each do |e| %>
              <li>
                <%= link_to room_path(e.room.id) do %>
                  <%= e.user.nickname %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      <% else %>
        <div class="show-bottom-left show-bottom-items c-box">
          <%= render "contact" %>
        </div>
      <% end %>

      <div class="show-bottom-center show-bottom-items c-box">
        <p>書き込んだ掲示板</p>
        <ul>
          <% @write_boards.each do |e| %>
            <li>
              <%= link_to e.title, board_path(e.id) %>
            </li>
          <% end %>
          <% if @write_boards.empty? %>
            <span>まだ書き込んだ掲示板はありません</span>
          <% end %>
          </ul>
      </div>

      <div class="show-bottom-right show-bottom-items c-box">
        <p>作成した掲示板</p>
        <ul>
          <% @create_boards.each do |e| %>
            <li>
              <%= link_to e.title, board_path(e.id) %>
            </li>
          <% end %>
          <% if @create_boards.empty? %>
            <span>まだ作成した掲示板はありません</span>
          <% end %>
          </ul>
      </div>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="show-right">
      <div class="show-right-top">
        <div class="recommend-title">
            <p>おすすめユーザー</p>
            <p><%= link_to 'ユーザー一覧', users_path %></p>
          </div>
        <%= link_to recommend_user_path(@user.id), class: "recommend-link" do %>
          <span class="recommend-link-text">もっと見る</span>
          <div>
            <%= image_tag 'sharp_keyboard_arrow_right_black_18dp.png', :size => '23x23' %>
          </div>
        <% end %>
      </div>
      <ul class="recommend-user-wrap c-box">
        <% @similar_user_limit.each do |e| %>
          <li class="recommend-user-item">
            <div class="recommend-user-left">
              <% if e.image.present? %>
                <div class="recommend-user-image"><%= image_tag e.image, class: "recommend-img img-back" %></div>
              <% else %>
                <div class="recommend-user-image"><%= image_tag "test.png", class: "recommend-img" %></div>
              <% end %>
            </div>
            <div class="recommend-user-right">
              <%= link_to e.nickname, user_path(e.id) %>
              <p><%= e.profile %></p>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>