config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'top#index'
  resources :top, only: :index
  resources :users, only: [:index, :show] do
    collection do
      get :setting
      get :nickname
      get :profileimage
      get :profile
      get :gameprofile
      get :email
    end
    member do
      get :followed, :followers, :recommend
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :boards do
    resources :comments, only: [:create, :destroy] 
  end
  resources :posts, only: [:new, :create]
  resources :rooms, only: [:index, :create, :show]
  resources :direct_messages, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :board_console_relations, dependent: :destroy
  has_many :board_category_relations, dependent: :destroy
  has_many :consoles, through: :board_console_relations
  has_many :categories, through: :board_category_relations

  validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :user_category_relations
  has_many :board_category_relations
  has_many :post_category_relations
  has_many :users, through: :user_category_relations
  has_many :boards, through: :board_category_relations
  has_many :posts, through: :post_category_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :content, presence: true, length: { in: 1..1000 }
end

app/models/console.rb
class Console < ApplicationRecord
  has_many :user_console_relations
  has_many :board_console_relations
  has_many :post_console_relations
  has_many :users, through: :user_console_relations
  has_many :boards, through: :board_console_relations
  has_many :posts, through: :post_console_relations
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :boards
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user
  has_many :post_console_relations, dependent: :destroy
  has_many :post_category_relations, dependent: :destroy
  has_many :consoles, through: :post_console_relations
  has_many :categories, through: :post_category_relations

  validates :message, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: { case_sensitive: true }, length: { maximum: 15 }

  has_one_attached :image
  has_many :boards
  has_many :comments

  has_many :user_console_relations
  has_many :consoles, through: :user_console_relations
  has_many :user_category_relations
  has_many :categories, through: :user_category_relations

  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy

  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :followers, through: :follower_relationships

  def self.guest
    find_or_create_by(nickname: 'ゲスト', email: 'guest@example.com', profile: "ゲストのプロフィール") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def followed?(other_user)
    followed_relationships.find_by(followed_id: other_user.id)
  end

  def follow(other_user)
    followed_relationships.create!(followed_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = followed_relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :move_to_index, only: [:edit, :destroy]
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @q = Board.ransack(params[:q])
    @boards = Board.all.page(params[:page]).per(20)
    @results = @q.result(distinct: true).page(params[:page]).per(20)
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.valid?
      @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @board.comments.includes(:user)
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to board_path
    else
      render :edit
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @board.user_id
      @board.destroy
      redirect_to root_path
    end
  end

  private

  def board_params
    params.require(:board).permit(:title, :game_id, console_ids: [], category_ids: []).merge(user_id: current_user.id)
  end

  def set_board
    @board = Board.find(params[:id])
  end

  def move_to_index
    @board = Board.find(params[:id])
    redirect_to root_path unless current_user.id == @board.user_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:message, :game_id, console_ids: [], category_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :recommend_function

  def index
    @boards = Board.order(created_at: 'DESC').limit(5)
    @posts = Post.order(created_at: 'DESC').limit(5)
    @user = current_user
    @category_ranks = Category.find(UserCategoryRelation.group(:category_id).order('count(category_id)desc').where.not(category_id: 10).pluck(:category_id))
  end

  def recommend_function
    if user_signed_in?
      user = current_user
      userCategories = user.user_category_relations
      myCategoryIds = []
      userCategories.each do |cate|
        myCategoryIds << cate.category.id
      end
      otherUserCategory = UserCategoryRelation.where(category_id: myCategoryIds).where('user_id !=?', user.id)
      otherUserIds = []
      otherUserCategory.each do |cate|
        otherUserIds << cate.user.id
      end
      userConsoles = user.user_console_relations
      myConsoleIds = []
      userConsoles.each do |con|
        myConsoleIds << con.console.id
      end
      otherUserConsole = UserConsoleRelation.where(console_id: myConsoleIds).where('user_id !=?', user.id)
      otherUserConsole.each do |con|
        otherUserIds << con.user.id
      end
      followedIds = user.followed_ids
      otherUserIds -= followedIds
      otherUserIds_uniq = otherUserIds.uniq
      @similar_user_limit = User.where(id: otherUserIds_uniq).limit(5)
      @similar_users = User.where(id: otherUserIds_uniq).page(params[:page]).per(10)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/edit.html.erb
<div class="board-wrap">
  <%= form_with model: @board, class: 'board-new-contents', local: true do |f| %>
    <h1 class="title">スレッド編集</h1>
    <div class="field">
      <label class="form-text">タイトル</label>
      <%= f.text_field :title, autofocus: true %>
    </div>

    <div class="field">
      <label class="form-text"><p>console（任意）</p></label><br>
      <div class='checkboxes checkbox-top'>
        <%= f.collection_check_boxes(:console_ids, Console.all, :id, :name) do |b| %>
          <label class='checkbox-console'><%= b.label {b.check_box + b.text} %></label>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label class="form-text"><br><p>category（任意）</p></label>
      <div class='checkboxes checkbox-middle'>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
          <label class='checkbox-category'><%= b.label {b.check_box + b.text} %></label><br>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label class="form-text"><p>game（任意）</p></label>
      <div class='checkboxes checkbox-middle'>
        <%= f.collection_select(:game_id, Game.all, :id, :name, :include_blank => "---") do |b| %>
          <label class='checkbox-category'><%= b.label {b.check_box + b.text} %></label><br>
        <% end %>
      </div>
    </div>

    <div class="btn register-btn">
      <%= f.submit "編集", class: "register-in-btn" %>
    </div>
  <% end %>
</div>

app/views/boards/index.html.erb
<div class="recommend-index">
  <div class="index-top">
    <p><%= link_to "トップページに戻る", root_path, class:"edit-link" %></p>
  </div>
  <div class="index-bottom">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">検索</div>
      </div>
      <div class="panel-body">
        <%= search_form_for @q do |f| %>
          <div class="row">
            <div class="form-group form-setting">
              <%= f.label :titel_cont, "タイトル" %>
              <%= f.text_field :title_cont, class: "form-control" %>
            </div>
          </div>
          <%= f.submit '検索', class: "btn btn-primary" %>
          <%= link_to 'クリア', url_for, class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
    <div class="user-show ">
      <ul class="users-wrap c-box">
        <% if params[:q].present? %>
          <div class="index-title">検索結果</div>
          <% if @results.empty? %>
            <p class="index-board-title">該当の掲示板が存在しません。</p>
          <% end %>
          <% @results.each do |result| %>
            <%= link_to board_path(result.id) do %>
              <li class="index-board-item">
                <p class="index-board-title"><%= result.title %></p>
              </li>
            <% end %>
          <% end %>
          <span><%= paginate @results %></span>
        <% else %>
          <div class="index-title">掲示板一覧</div>
          <% @boards.each do |board| %>
            <%= link_to board_path(board.id) do %>
              <li class="index-board-item">
                <p class="index-board-title"><%= board.title %></p>
              </li>
            <% end %>
          <% end %>
          <span><%= paginate @boards %></span>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="board-wrap">
  <%= form_with model: @board, url: boards_path, class: 'board-new-contents', local: true do |f| %>
  <h1 class="title">新規スレッド作成</h1>
    <div class="field">
      <label class="form-text">タイトル:</label>
      <%= f.text_field :title, autofocus: true %>
    </div>

    <div class="field">
      <label class="form-text"><p>console（任意）</p></label><br>
      <div class='checkboxes checkbox-top'>
        <%= f.collection_check_boxes(:console_ids, Console.all, :id, :name) do |b| %>
          <label class='checkbox-console'><%= b.label {b.check_box + b.text} %></label>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label class="form-text"><br><p>category（任意）</p></label>
      <div class='checkboxes checkbox-middle'>
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
          <label class='checkbox-category'><%= b.label {b.check_box + b.text} %></label><br>
        <% end %>
      </div>
    </div>

    <div class="field">
      <label class="form-text"><p>game（任意）</p></label>
      <div >
        <%= f.collection_select(:game_id, Game.all, :id, :name, :include_blank => "---") do |b| %>
          <label><%= b.label {b.check_box + b.text} %></label><br>
        <% end %>
      </div>
    </div>

      <div class="btn register-btn">
      <%= f.submit "作成", class: "register-in-btn" %>
    </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<%# <%= render "shared/second_header" %>

<div class="board-main">
  <div class="redirect-top">
    <%= link_to 'トップページに戻る', root_path %>
  </div>
  <div class="board-show">
    <div class="board-info">
      <div class="thread-header">
        <p class="board-title"><%= @board.title %></p>
        <div class="edit-thread">
          <% if user_signed_in? && current_user.id == @board.user_id %>
            <ul>
              <li><%= link_to '編集', edit_board_path(@board.id) %></li>
              <li><%= link_to '削除', board_path(@board.id), method: :delete %></li>
            </ul>
          <% end %>
        </div>
      </div>
      <ul class="board-content">
        <li class="board-create">作成者:<%= @board.user.nickname %></li>
        <li class="board-create"><%= @board.created_at.strftime("%Y/%m/%d") %></li>
      </ul>
    </div>

    <div class="comment-wrap">
      <% if @board.comments.empty? %>
        コメントはまだありません
      <% else %>
        <% @comments.each_with_index do |comment, index| %>
          <div class="comment-show c-box">
            <div class="comment-header">
              <ul class="comment-header-left">
                <li class="comment-left-content"><%= 1 + index %></li>
                <li class="comment-left-content"><%= comment.user.nickname %></li>
                <li class="comment-left"><%= time_ago_in_words(comment.created_at) + '前' %></li>
              </ul>
              <ul class="comment-header-right">
                <li class="comment-right-content"><%= comment.created_at.strftime("%Y/%m/%d %H:%M") %></li>
                <li class="comment-right-content">
                  <% if user_signed_in? && current_user.id == comment.user_id %></li>
                    <%= link_to '削除', board_comment_path(@board, comment), method: :delete %>
                  <% end %>
                </li>
              </ul>
            </div>
            <div class="comment-content">
              <p><%= safe_join(comment.content.split("\n"),tag(:br)) %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="input-comment">
      <% if user_signed_in? %>
        <%= form_with model: [@board, @comment], class: "form-comment", local: true do |f| %>
          <label class="form-text">コメント:</label>
          <div class="input-content ">
            <%= f.text_area :content, class: "content-custom" %>
          </div>
          <div class="btn register-btn">
            <%= f.submit '投稿する', class: "register-in-btn" %>
          </div>
        <% end %>
      <% else %>
        書き込むにはログインが必要です
        <%= link_to 'ログイン', new_user_session_path %>
      <% end %>
    </div>

  </div>
</div>