config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'top#index'
  resources :top, only: :index
  resources :users, only: [:index, :show] do
    collection do
      get :setting
      get :nickname
      get :profileimage
      get :profile
      get :gameprofile
      get :email
    end
    member do
      get :followed, :followers, :recommend
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :boards do
    resources :comments, only: [:create, :destroy] 
  end
  resources :posts, only: [:new, :create]
  resources :rooms, only: [:index, :create, :show]
  resources :direct_messages, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :board_console_relations, dependent: :destroy
  has_many :board_category_relations, dependent: :destroy
  has_many :consoles, through: :board_console_relations
  has_many :categories, through: :board_category_relations

  validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :user_category_relations
  has_many :board_category_relations
  has_many :post_category_relations
  has_many :users, through: :user_category_relations
  has_many :boards, through: :board_category_relations
  has_many :posts, through: :post_category_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :content, presence: true, length: { in: 1..1000 }
end

app/models/console.rb
class Console < ApplicationRecord
  has_many :user_console_relations
  has_many :board_console_relations
  has_many :post_console_relations
  has_many :users, through: :user_console_relations
  has_many :boards, through: :board_console_relations
  has_many :posts, through: :post_console_relations
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :boards
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :game, optional: true
  belongs_to :user
  has_many :post_console_relations, dependent: :destroy
  has_many :post_category_relations, dependent: :destroy
  has_many :consoles, through: :post_console_relations
  has_many :categories, through: :post_category_relations

  validates :message, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: { case_sensitive: true }, length: { maximum: 15 }

  has_one_attached :image
  has_many :boards
  has_many :comments

  has_many :user_console_relations
  has_many :consoles, through: :user_console_relations
  has_many :user_category_relations
  has_many :categories, through: :user_category_relations

  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy

  has_many :followed_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :follower_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :followed_relationships
  has_many :followers, through: :follower_relationships

  def self.guest
    find_or_create_by(nickname: 'ゲスト', email: 'guest@example.com', profile: "ゲストのプロフィール") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def followed?(other_user)
    followed_relationships.find_by(followed_id: other_user.id)
  end

  def follow(other_user)
    followed_relationships.create!(followed_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = followed_relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :recommend_function

  def index
    @boards = Board.order(created_at: 'DESC').limit(5)
    @posts = Post.order(created_at: 'DESC').limit(5)
    @user = current_user
    @category_ranks = Category.find(UserCategoryRelation.group(:category_id).order('count(category_id)desc').where.not(category_id: 10).pluck(:category_id))
  end

  def recommend_function
    if user_signed_in?
      user = current_user
      userCategories = user.user_category_relations
      myCategoryIds = []
      userCategories.each do |cate|
        myCategoryIds << cate.category.id
      end
      otherUserCategory = UserCategoryRelation.where(category_id: myCategoryIds).where('user_id !=?', user.id)
      otherUserIds = []
      otherUserCategory.each do |cate|
        otherUserIds << cate.user.id
      end
      userConsoles = user.user_console_relations
      myConsoleIds = []
      userConsoles.each do |con|
        myConsoleIds << con.console.id
      end
      otherUserConsole = UserConsoleRelation.where(console_id: myConsoleIds).where('user_id !=?', user.id)
      otherUserConsole.each do |con|
        otherUserIds << con.user.id
      end
      followedIds = user.followed_ids
      otherUserIds -= followedIds
      otherUserIds_uniq = otherUserIds.uniq
      @similar_user_limit = User.where(id: otherUserIds_uniq).limit(5)
      @similar_users = User.where(id: otherUserIds_uniq).page(params[:page]).per(10)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oriapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
  <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/user_edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oriapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
  <%= render "shared/header" %>
  <div class="setting-wrap">
    <div class="setting-wrap">
      <div class="setting-sub c-box">
        <div class="setting-sub-top">
          <div class="setting-user-image">
            <% if current_user.image.present? %>
              <div class="setting-image"><%= image_tag current_user.image, class: "set-img img-back" %></div>
            <% else %>
              <div class="recommend-user-image"><%= image_tag "test.png", class: "set-img" %></div>
            <% end %>
          </div>
          <p><%= current_user.nickname %></p>
        </div>
      </div>
      <div class="setting-main">
        <%= yield %>
      </div>
    </div>

    <div class="show-right">
      <div class="show-right-top">
        <div class="recommend-title">おすすめユーザー</div>
        <%= link_to users_path, class: "recommend-link" do %>
          <span class="recommend-link-text">もっと見る</span>
          <div>
            <%= image_tag 'sharp_keyboard_arrow_right_black_18dp.png', :size => '23x23' %>
          </div>
        <% end %>
      </div>
      <ul class="recommend-user-wrap c-box">
        
          <li class="recommend-user-item">
            <div class="recommend-user-left">
              <div class="recommend-user-image">image</div>
            </div>
            <div class="recommend-user-right">
              
            </div>
          </li>
      </ul>
    </div>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='header-top'>
    <ul class='lists-left'>
      <li><%= link_to image_tag("controller01.png", class:"header-icon"), "/" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "login" %></li>
        <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second_header.html.erb
<div class='second-header'>
  <% @consoles.each do |console| %>
    <ul class="console-wrapper">
      <li class='console-name'><%= link_to console.name, "#" %></li>
    </ul>
  <% end %>
</div>